# Generated by Django 4.0.4 on 2022-04-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='image',
            new_name='imagen',
        ),
    ]
