# Generated by Django 4.0.4 on 2022-04-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_rename_image_servicio_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='update',
            new_name='updated',
        ),
    ]
