# Generated by Django 4.0.4 on 2022-05-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_servicio_contenido_alter_servicio_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
